### ISSUE TITLE
Error running filter abstract-section: Could not find executable abstract-section

### ISSUE THREAD

**Issue by fBedecarrats** [pandoc-ext/abstract-section#1]
Hello and thanks for this cool extension that seems useful.

I am running Quarto in RStudio on an Ubuntu 22.04, with 2022.12.0, R 4.2.2 and quarto 1.2.269.
As per your README, I installed the extension using the terminal: 
``` bash
onyxia@rstudio-32255-0:~/work$ quarto install extension pandoc-ext/abstract-section

Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
pandoc-ext/abstract-section   [Install]   1.0.0 (filter)
 ? Would you like to continue (Y/n) › Yes

[✓] Extension installation complete.
Learn more about this extension at https://www.github.com/pandoc-ext/abstract-section
```

Then I create a `test.qmd` file:

``` quarto
---
title: "test"
format: html
editor: visual
filters:
  - abstract-section
---

# Abstract

This is my abstract

****

# Introduction

This is my introduction.
```
But when I try to render it, I get the following error:

``` bash
onyxia@rstudio-32255-0:~/work/trends_pa_types$ quarto render test.qmd
pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: test
  editor: visual
  
Error running filter abstract-section:
Could not find executable abstract-section
```
Any idea of how to solve this?

**Comment by tarleb** [comment]
Quarto does not install extensions globally, but per-project. The advantage is that older projects will continue to work, even if a new, incompatible version of an extension has been released in the meantime.

Try to run the `install` step in your project folder `~/work/trends_pa_types`.

**Comment by fBedecarrats** [comment]
Thank you very much for this answer. I can confirm that it works in a Linux environment. I would suggest completing the readme to specify that the installation must be done within the project folder. 
I have different problems with the extension on Windows. I am opening a separate issue for this.
