### ISSUE TITLE
Abstract causes font size to shrink in paragraphs with margins and without footnotes

### ISSUE THREAD

**Issue by sebastian-c** [pandoc-ext/abstract-section#3]
Font size changes unexpectedly because this extensions causes paragraphs to not be wrapped in the right `div`.

# Faulty behaviour

```md
---
title: "Test"
format: 
  html:
    reference-location: margin
    self-contained: true
filters:
- abstract-section
---

# Abstract

This is an abstract

## A title

Here is some text without a footnote

Here is some text with a footnote^[Look, a footnote]
```

![image](https://user-images.githubusercontent.com/1818581/229546142-027da91f-4fa2-41a0-a1a8-a755594bd3b8.png)

# Desired behaviour

```md
---
title: "Test"
format: 
  html:
    reference-location: margin
    self-contained: true
---

---
abstract: |
  This is an abstract
---

## A title

Here is some text without a footnote

Here is some text with a footnote^[Look, a footnote]
```
![image](https://user-images.githubusercontent.com/1818581/229545722-d0efe1b7-3fa3-48f7-b158-312248dc5dab.png)

**Comment by tarleb** [comment]
There is a slight misunderstanding in how the filter works: some abstracts do contain headings, so everything up to the next top-level heading is included in the abstract. The result of applying the filter is equivalent to

``` yaml
---
abstract: |
  # Abstract

  This is an abstract

  ## A title

  Here is some text without a footnote

  Here is some text with a footnote^[Look, a footnote]
---
```

Use a horizontal rule if you want the abstract to end before the next level 1 heading:

``` markdown
# Abstract

This is an abstract

* * * * *

## A title

Here is some text without a footnote

Here is some text with a footnote^[Look, a footnote]
```

The font/footnote issue is weird, but unrelated to this filter. I suggest to report it in [quarto-cli](https://github.com/quarto-dev/quarto-cli).
