### ISSUE TITLE
Mutiple section not woring for docx

### ISSUE THREAD

**Issue by 0xffmeta** [pandoc-ext/abstract-section#5]
I'm using the test input file: [input-two-sections.md](https://github.com/pandoc-ext/abstract-section/blob/main/test/input-two-sections.md)
Then I run the pandoc cmd in window: (I don't know how to install extention for pandoc, so I have to download this filter locally or is there any other way to install?)
`pandoc -L abstract-section.lua input-two-sections.md -f markdown -t docx -o test1.docx`

The output is:
![image](https://github.com/pandoc-ext/abstract-section/assets/98149057/4f1f92ee-ab01-484a-bdd4-2257033d87c2)

**Comment by tarleb** [comment]
All this filter does is to move the abstract sections to the metadata fields. As noted in the README, multiple abstracts will generally require custom templates. However, pandoc does not support custom templates for docx at the moment, so there isn't an easy way to make this work. Sorry.
